.Dd June 23, 2026
.Dt SMDEVINFO 1
.Os
.Sh NAME
.Nm smdevinfo
.Nd determines information about a storage media (SM) device
.Sh SYNOPSIS
.Nm smdevinfo
.Op Fl hvV
.Ar source
.Sh DESCRIPTION
.Nm smdevinfo
is a utility to determine information about a storage media (SM) device
.Pp
.Nm smdevinfo
is part of the
.Nm libsmdev
package.
.Nm libsmdev
is a library to access and read storage media (SM) devices
.Pp
.Ar source
is the source device.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl h
shows this help
.It Fl v
verbose output to stderr
.It Fl V
print version
.El
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh EXAMPLES
.Bd -literal
# sudo smdevinfo /dev/sdg
smdevinfo 20130329
.sp
Device information:
	bus type		: USB
	vendor			: TestCo
	model			: TEST-98Z7YX6
	serial			: 123A45678B9C
.sp
Storage media information:
	media type		: Fixed
	media size		: 931 GiB (1000204886016 bytes)
	bytes per sector	: 4096
.sp
.Ed
.Sh DIAGNOSTICS
Errors, verbose and debug output are printed to stderr when verbose output \
\-v is enabled.
Verbose and debug output are only printed when enabled at compilation.
.Sh AUTHORS
.An Joachim Metz <joachim.metz@gmail.com>
.Sh BUGS
Please report bugs of any kind on the project issue tracker: \
https://github.com/libyal/libsmdev/issues
.Sh COPYRIGHT
Copyright (C) 2010-2026, Joachim Metz <joachim.metz@gmail.com>.
.sp
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A \
PARTICULAR PURPOSE.
